spring:
  application:
    name: franchise-backend-system
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/franchise_backend}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
